chore(ci): update Renovate configuration and enhance HCL formatting checks

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -10,10 +10,19 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
-        uses: actions/checkout@v4
+        uses: actions/checkout@main
+
+      - name: Set up Nomad
+        uses: hashicorp/setup-nomad@main
 
       - name: Fail on malformatted files
-        uses: devops-infra/action-format-hcl@master
-        with:
-          check: true
-          write: false
+        run: |
+          EXIT_CODE=0
+          while IFS= read -r file; do
+            echo "Checking $file"
+            if ! nomad fmt -list=false -write=false -check "$file" &>/dev/null ; then
+              echo "::error file=$file::File is not properly formatted"
+              EXIT_CODE=1
+            fi
+          done < <(find . -type f -name "*.hcl")
+          exit $EXIT_CODE
